# Generated by Django 4.2.29 on 2026-03-21 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(default='user', max_length=16)),
                ('source_identifier', models.CharField(max_length=128)),
                ('kubernetes_username', models.CharField(blank=True, max_length=128)),
                ('kubernetes_groups', models.JSONField(blank=True, default=list)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_mappings', to='clusters.cluster')),
            ],
            options={
                'unique_together': {('source_type', 'source_identifier', 'cluster')},
            },
        ),
    ]
