# Generated by Django 4.2.29 on 2026-03-21 03:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=72, unique=True)),
                ('environment', models.CharField(default='development', max_length=32)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('server', models.URLField(max_length=512)),
                ('default_context', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=16)),
                ('health_state', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('kube_version', models.CharField(blank=True, max_length=64)),
                ('last_error', models.TextField(blank=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClusterHealthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='clusters.cluster')),
            ],
        ),
        migrations.CreateModel(
            name='ClusterCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_context', models.CharField(max_length=255)),
                ('kubeconfig_encrypted', models.TextField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='clusters.cluster')),
            ],
        ),
        migrations.CreateModel(
            name='ClusterCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supports_impersonation', models.BooleanField(default=False)),
                ('supports_server_side_apply', models.BooleanField(default=True)),
                ('supports_watch_bookmarks', models.BooleanField(default=True)),
                ('supports_exec', models.BooleanField(default=False)),
                ('discovered_api_groups', models.JSONField(blank=True, default=list)),
                ('openapi_index', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('cluster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capability', to='clusters.cluster')),
            ],
        ),
    ]
