apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kuboard.fullname" . }}-secret
  labels:
    {{- include "kuboard.labels" . | nindent 4 }}
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ .Values.backend.secretKey | quote }}
  KUBOARD_ENCRYPTION_KEY: {{ .Values.backend.encryptionKey | quote }}
  KUBOARD_ADMIN_EMAIL: {{ .Values.backend.admin.email | quote }}
  KUBOARD_ADMIN_PASSWORD: {{ .Values.backend.admin.password | quote }}
  KUBOARD_ADMIN_DISPLAY_NAME: {{ .Values.backend.admin.displayName | quote }}

