# Generated by Django 4.2.29 on 2026-03-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamsession',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streamsession',
            name='command',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='streamsession',
            name='container_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='streamsession',
            name='exit_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streamsession',
            name='namespace',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='streamsession',
            name='output_excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='streamsession',
            name='resource_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='streamsession',
            name='status',
            field=models.CharField(default='running', max_length=16),
        ),
    ]
